### ISSUE TITLE
Sharing trained models

### ISSUE THREAD

**Issue by Trabel** [deepfakes/faceswap-playground#103]
Hello there! Can somebody share trained models please? Or where can I find this stuff? (I know about trained models in the fase-swap.zip, I am talking about other variants, better quality) Coz I use Amazon's GPU and it's so expensive duh, and it take so much money for training=(

**Comment by bryanlyon** [comment]
Sharing models is allowed and certainly feasible.  The problem is that models are specific to the actors involved.  I'd happily share my models, but they're incomplete and mostly experimental.  Is there a specific actor-actor model you're interested in?

There are a lot of really good Nicolas Cage models if you're interested I'm sure someone can post one or two.

The big problem is that models are 200MB + so we can't really upload all of them without first knowing exactly what model is needed.

**Comment by Trabel** [comment]
Yes, models are specific to certain actors, but as I understood, training become more and more faster after more and more training cycles for one model. Is it right?

**Comment by bryanlyon** [comment]
No, that is not right. It actually takes time to unlearn on actor to learn about.  Unless they already look very similar, it is unlikely to create good results in with a long time.  Even then, you'll get results from the original model.  Better to start from scratch than mistrain a model.  Unless you want to combine multiple faces to create a hybrid (child of) type face replacement.
