### ISSUE TITLE
Is there a good description of exactly how this works somewhere?

### ISSUE THREAD

**Issue by frosty3907** [deepfakes/faceswap-playground#124]
I think it would help development and understanding if there was a reasonably detailed description of exactly what is occurring during training, I've heard many different explanations but they're usually vague and often conflicting.

For example; I'm still unsure if you should train with images in data_A of the 'celeb' that won't be in the final clip, also- regarding obstructions of the face, is it OK to use these as source images if the destination face also has similar obstructions at times in it's dataset?

**Comment by Kirin-kun** [comment]
Answer: how it works depends on the model.

As for you other questions: you can train with images in data_A that won't be in the final clip. What's important is the pose and if the NN is able to predict it. Ie, you can use the same saved model to put a face on different targets (at least in original model) without retraining, but result will depend on the poses the NN learned.

And if you have obstruction, probably the GAN model is more suited. Because original model will learn useless things with obstruction and it will average it with the rest. And that's probably not what you want.

**Comment by bryanlyon** [comment]
This is an old issue but before I close it I want to put in that you can get advice like this on the official Discord at https://discord.gg/FdEwxXd
