### ISSUE TITLE
New ai technique from Nvidia

### ISSUE THREAD

**Issue by bryanlyon** [deepfakes/faceswap-playground#142]
https://arxiv.org/abs/1804.07723

This may be an interesting way to fill in details like eyes or teeth that other people have complained about.  I'm not sure how much the work they did will translate to our needs, mostly in implementation and training seems to be quite extensive, but it might be a good direction to go once faceswap is solid.

**Comment by b4nn3d** [comment]
also this model, always from nvidia 
https://github.com/deepfakes/faceswap-model/issues/25

**Comment by Kirin-kun** [comment]
I read the paper and it's really interesting but it looks like it's more about removing occlusion than masking it. And it would involve 2 pass learning? One to "un-occlude" the faces, the other to learn to swap.

Instead of adding another layer or deeplearning right away, a good starting point would be to see what would be the results of [PatchMatch](https://en.wikipedia.org/wiki/PatchMatch) which is the state of the art for patching regions, but, according to the paper "these methods can only handle narrow holes, where the color and texture variance is small"

Well, mouth/teeth and eyes are just that.

That's what we were thinking at first in https://github.com/deepfakes/faceswap/issues/296 

Since we have a huge amount of reference images to patch the dst, that maybe easier and faster to post-process the converted faces before applying them.

**Comment by Kirin-kun** [comment]
Interestingly, there are a lot of implementations of PatchMatch

https://github.com/matthew-cox/PatchMatch-CUDA
