### ISSUE TITLE
Recreating speaking face in the same video (instead of just swapping face)

### ISSUE THREAD

**Issue by ashray** [deepfakes/faceswap-playground#143]
I recently stumbled upon this video - 
https://www.youtube.com/watch?v=cQ54GDm1eL0

As far as I understand, what the faceswap code might do will be to replace the new speaker's face onto Obama's original video. What if we instead want to create a video like the one above? Is it possible to just "swap" the mouth area of Obama from some different parts of the video?

To generate the lip points we can use something like this - 
http://grail.cs.washington.edu/projects/AudioToObama/ but how to go from lip points to the video (using Machine learning) is something I am still trying to figure out.

**Comment by bonlime** [comment]
I'm not sure which method they used in video provided. Maybe it was something like this: https://www.youtube.com/watch?v=ohmajJTcpNk&t=2s ? instead of faceswap

**Comment by bryanlyon** [comment]
This was done by Jordan Peele and uses traditional VFX techniques.  That means they hired a VFX team to manually edit Obama's face and stuck Peele's mouth on to it.  They were careful in how they selected the script so that it would line up with the video they already had of Obama talking.

This was not done with any AI tools faceswap, or otherwise.  It's good old-fashioned Hollywood magic.

**Comment by sg2308** [comment]
Or you may check [this repo](https://github.com/datitran/face2face-demo) . This tries to use ai for the same . But results are not good when i tried to replicate on my machine.

**Comment by bryanlyon** [comment]
https://github.com/albertpumarola/GANimation is now the state of the art in this field.  It looks pretty good but requires full training on a huge dataset.  We might be implementing some of the ideas from this into a new model.
