### ISSUE TITLE
Image Symmetry?

### ISSUE THREAD

**Issue by samsonsite1** [deepfakes/faceswap-playground#186]
Does face swapping understand image symmetry, or in other words, a horizontally flipped image?

For example, if modelA has a face looking in the left direction, and modelB has a similar face, but it's looking in the right direction, would it be able to flip modelB to match modelA ?

Let's say I have no samples of modelB looking in the left direction.  Would horizontally flipping an image improve my training results?

**Comment by Kirin-kun** [comment]
faceswap applies random transform to face pictures during the training process, including flipping them.

See [random_transform function here](https://github.com/deepfakes/faceswap/blob/master/lib/training_data.py) and [random_transform_args here](https://github.com/deepfakes/faceswap/blob/master/plugins/Model_Original/Trainer.py)

**Comment by bryanlyon** [comment]
This is an essential part of the reconstruction.  It needs to warp the faces in order to get the model to train against them.  Training works by first distorting the images, then training a neural network to reconstruct them.  It's this same network that converts the face to another.

Horizontal swapping could improve quality, but will not be anywhere bear as good as finding a

**Comment by bryanlyon** [comment]
I apologise for closing the issue, it was accidental.

**Comment by samsonsite1** [comment]
So, you're saying the images are flipped, but only through random chance?  But, if I supplied the flipped images directly, not by random chance, would that somehow speed up the process, or slow it down?
