### ISSUE TITLE
Training db for person B - benefit of including non-video images

### ISSUE THREAD

**Issue by flipflopbboi** [deepfakes/faceswap-playground#211]
Hello all,
quick question: 
Lets assume I want to swap face of person A to body of person B in a video of small duration (e.g. 20 seconds -> 600 frames).
what should be included in person B's training db? 
(i)  only extracted faces from the video? 
(ii) extracted face from the video + other sources in different lighting etc.
Is there a rule of thumb regarding size/relative size of training db for A and B e.g. should we strive to have similar number of images in both A and B, as diverse lighting/angles as possible etc.?
Your comments are appreciated! thanks

**Comment by bryanlyon** [comment]
The best place to get advice like this is at the discord https://discord.gg/WZTYz8 since it varies based on your needs.

But basics: I recommend at least 1000 images/frames for each A and B.  Video is better since photos tend to be posed, but photos can help get details if the videos you have are low res.  Your datasets A and B should be similar in size or you'll be skewing the model.  You should pick your frames based on the video(s) you want to swap in.

Come to the Discord if you want more detailed/better answers.
