### ISSUE TITLE
How to determine - GPU or CPU is used?

### ISSUE THREAD

**Issue by qzmenko** [deepfakes/faceswap-playground#22]
Hello.

During the installation, I made a mistake and first started:

> pip install -r requirements.txt

After that I run:

> pip install -r requirements-gpu.txt

When I start training, I have such messages:
> ...
> Model A Directory: /Volumes/HDD/faceswap/source_faces
> Model B Directory: /Volumes/HDD/faceswap/target_faces
> Training data directory: /Volumes/HDD/faceswap/model
> 2018-01-31 03:37:14.842407: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
> Starting, this may take a while...
> press "q" to stop training and save model

I'm confused by this line:
> 2018-01-31 03:37:14.842407: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 

Does this mean that the training was started using the CPU?

**Comment by flip1995** [comment]
Yes you are using the CPU. This is porbably because you first installed the `requirements.txt` and then the `requirements-gpu.txt` file. 
If you're on Windows making this work on the GPU is a pain in the ***. 

If you have set up everything to be able to run this on the GPU, try this:
You should have only installed one of them. Try running
```bash
pip3 uninstall tensorflow
```
and then try running faceswap again. If it uses the gpu you will get a message, where it tells you which GPU it uses.

**Comment by Clorr** [comment]
you can try nvidia tools to see if GPU is running. On the CLI you have `nvidia-smi` also
