### ISSUE TITLE
Question to swap model A>B (using GAN)?

### ISSUE THREAD

**Issue by Ianmcmill** [deepfakes/faceswap-playground#71]
Just a general question regarding swaping the model.
In convert using -s the model is supposed to swap the faces the other way around.
I tried to replace person B's face with person A's face. So the other way everybody is normally trying to but the result is that person B's face is replaced with itself (B->B).

What I am doing wrong? Did I get something wrong with the -s option?

**Comment by Clorr** [comment]
The GAN model has [limitations on swapping](https://github.com/deepfakes/faceswap/blob/819d10702a8253aec228b8083cdd0857f28e548d/plugins/Model_GAN/Model.py#L170) because the load of model is done within the init part. However I thought that it could be solved in the [converter](https://github.com/deepfakes/faceswap/blob/819d10702a8253aec228b8083cdd0857f28e548d/plugins/Model_GAN/Model.py#L66) part, but it seems not to be the case. It is quite a hard work to move the GAN notebooks to this repo, so I hope we can enhance this later, but I'm giving up for now
