### ISSUE TITLE
GPU choosing

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap-playground#90]
I have two gpus now,
gtx1060 and gt 730 

https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/
env param CUDA_VISIBLE_DEVICES info:
```
CUDA_VISIBLE_DEVICES=1           Only device 1 will be seen
CUDA_VISIBLE_DEVICES=0,1         Devices 0 and 1 will be visible
CUDA_VISIBLE_DEVICES="0,1"       Same as above, quotation marks are optional
CUDA_VISIBLE_DEVICES=0,2,3       Devices 0, 2, 3 will be visible; device 1 is masked
CUDA_VISIBLE_DEVICES=""          No GPU will be visible
```

I set this env vars

```
SET TF_MIN_GPU_MULTIPROCESSOR_COUNT=2
SET CUDA_VISIBLE_DEVICES=1
```

so I just ran extract 4k photos on my GT 730 2gb, with compute cap 3.5, while gtx1060 training model.

![python_2018-03-07_14-54-40](https://user-images.githubusercontent.com/8076202/37088788-ed8c826c-2217-11e8-9e7c-0edb3ebe2ba2.png)

so what if add param to command line like `--cuda-devices="0,1" `
and set to `os.env["CUDA_VISIBLE_DEVICES"] = arg` before any CUDA initialization
so we can easy get multi gpu support to FaceSwap ?
@Clorr

**Comment by Clorr** [comment]
Any improvment is welcome ;-)

**Comment by bryanlyon** [comment]
If you want to limit which GPUs to use, I recommend doing it on your own with that environment variable.  If we set the variable, it will persist and could cause confusion as to why other applications are not using all GPUs.

There are other ways to restrict GPU usage inside the app itself, but it is not implemented at this time due to the amount of architectural changes it would require.

The easiest solution is to set the variable yourself and run the program.  If you don't want to do it every time, you could make a batch script (or bash script for Linux) that sets the variable and then starts faceswap.
