### ISSUE TITLE
Has anyone had good results with masked GAN?

### ISSUE THREAD

**Issue by Apollo122** [deepfakes/faceswap-playground#98]
I'm training a GAN-64 model expecting to get face obstructions handled but no luck. Options, perception loss and instance normalization are on and it has been trained for 20k ite with large image set (A-16k, B-9k). Do you think is it because i included those frames (I thought model needed to learn from those frames) or bad port or maybe it just works for simple cases and greatly exaggerated in original gan repo?
I'm really curious that if there is anyone who succeed in this.

**Comment by bryanlyon** [comment]
My GAN experience is limited, but my suggestion on general ai tasks is to
do a long training on related data but not the actual data (so faces of the
same person, but from different videos) you're going to use, then after a
good training, do another, shorter training on the actual video data you're
swapping.  This gives the model a limited opportunity to overtrain on the
dates you're using.

You may be giving it too many faces, the more you give it, the longer it'll
take to train, even if it's the same person.  It's better to use a few
hundred good shots instead.  Make sure to get a variety of lighting and
directions for the great results.

On Mar 13, 2018 3:05 PM, "Apollo122" <notifications@github.com> wrote:

I'm training a GAN-64 model expecting to get face obstructions handled but
no luck. Options, perception loss and instance normalization are on and it
has been trained for 20k ite with large image set (A-16k, B-9k). Do you
think is it because i included those frames (I thought model needed to
learn from those frames) or bad port or maybe it just works for simple
cases and greatly exaggerated in original gan repo?
I'm really curious that if there is anyone who succeed in this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/deepfakes/faceswap-playground/issues/98>, or mute the
thread

**Comment by ruah1984** [comment]
i have train up to 50k ite before for a few days, preview looks not bad, but after convert with mask , looks bad and not actually like what shaoanlu show in his preview, maybe we miss up something

**Comment by bryanlyon** [comment]
All of our work is experimental, don't use anything here for another that
matters.  This is not a magical tool, it's a learning experience.

That said, GAN and IAE are both new adds.  We'll be fixing bugging at least
for a few weeks before they'll be stable.

If you NEED results and want them consistent, then yes, stick with
original.  The other models are not as stable as the original model yet.

As we move on, the models and software will get better, that's the point.
We'd never get anywhere if we didn't try new models.

On Mar 14, 2018 00:22, "Apollo122" <notifications@github.com> wrote:

Trying these new trainers has been completely waste of time. First I tried
IAE results were horrible, and now GAN. In my opinion original trainer is
still best and stable. And I think GAN merge was a mistake. Couple of
people including me reportted there are problems with GAN regarding mask.
If mask has problems there is a good possibility that other parts have
problems too considering this is a port. It got merged anyway and it's
useless

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/deepfakes/faceswap-playground/issues/98#issuecomment-372927500>,
or mute the thread

**Comment by Apollo122** [comment]
If they are not stable why did they get merged to master then? I agree they are experimental, I tested the GAN PR. I'm just saying it is a mistake to merge trainers before knowing that for sure they are working and stable.

**Comment by ruah1984** [comment]
I try shaoanlu GAN and compare with this GAN Repo, with 15k samples,>50k itr unfortunately cant get a better face. i think if GAN willl need to train more and more. i will advice don't look at the preview window, preview window looks good, convert not means good. we shall try some sample convert after run certain times

**Comment by bryanlyon** [comment]
They got merged so everyone could use them.  They're optional and we're
doing our best to support them.  We'll get them there, just give us time.

**Comment by bryanlyon** [comment]
We should be able to match the convert to what you see in preview, just a
lot to figure out and check.  The preview is a representation of what the
model sees, we're just having trouble getting it out, it's a technical
problem, and a surmountable one.

**Comment by ruah1984** [comment]
I know is on the way, i not too worry about it. For me is too bad that, https://github.com/deepfakes/faceswap/pull/246 option not include to the latest repo. i have try this before, it actually help a little bit on the training , with same itr .@iperov do a great job,  hope he can re-open back this and merge with the master.

**Comment by Clorr** [comment]
@Apollo122 I understand your point as I think you see the project as an out-of-the-box ready tool for end-users. I do not see it this way.

First, the work of contributors, whether they add code or just help others (as you do) is much more important to me than leechers who come complain and don't even bother to let an improvment after they have succeeded. So someone who did something, pushes a PR and says "I have put some of my brain time on this, now I think it is ready, and I can't go much further" is already to be considered. If it's work is not perfect, I don't care as long as it is good enough.

Second thing, by providing a pluggable architecture, I sent a message to programmers to say "Hey guys, come in! You can also add something of your own, and if not, you can also get inspiration from previous users and improve things". This way I try to lower the number of hard forks like GAN or DFaker (which started before this repo has grown) but also I offer a possibility to new programmers to be able to see the different approaches and maybe get inspired to see a better solution. Also, what's not perfect today can help someone and can be improved tomorrow; what is not published won't ever be improved. And if you set too high expectations in accepting new code, you will discourage many people from publishing.

Also I think if Original was perfect we wouldn't have to discuss about this. Maybe it is the best for most cases today, but still it needs refining. And that's why I want people to publish (and this is also why I put [DRAFT] and [experiment] PRs)

Maybe some day we will have tens of active contributors, many projects based on the repo, and this day the politics will change. However for now, it is still a WIP

**Comment by Apollo122** [comment]
@Clorr I understand what you are saying and yeah people who help others or push code are valuable and I would never want to discouraged them in fact I argued some people who do that in repo. But I don't agree that merging to master would make the code better. Merging to master should be last step though I'm seeing this approach with new PR's and it's a good thing. I actually specifically criticize the GAN merge even @oatssss commented that he was getting different results from the original repo. In my opinion It needed more time and wasn't ready thats all what I'm saying. Maybe we can create another branch and merge these experimental stuff there? Most open-source projects have stable and experimental branches.

**Comment by Clorr** [comment]
@oatss had much work on his PR and I didn't want to let him on it forever. It's a very big work to do that and we don't have so much skilled contributors. So it is fair enough that his work is merged and that he can move on to something else (or can improve GAN with peace of mind).

I agree that at some point we can have an experimental branch but I let that to contributors who want to work this way. And the problem with experimental branch + few users is that anyway, you will have people waiting for the code to be in master and that will only test and feedback when code is in master.

For plugins, as it is optional and that users can deliberately choose their prefered way of training it, one should try a plugin, see if he is satisfied with it. If not, he can contribute or move on to another option.

**Comment by iperov** [comment]
@shaoanlu
is this good mask ?

![python_2018-03-17_16-36-26](https://user-images.githubusercontent.com/8076202/37555517-aba897f4-2a01-11e8-8886-986a8c763b0b.png)

**Comment by Apollo122** [comment]
@iperov have you tried with obstructions such as hands in front of the face? Do they get blurred or you can see the hands clearly?

**Comment by iperov** [comment]
not yet

**Comment by iperov** [comment]
@oatssss is there any color bug with converting ?

![python_2018-03-17_18-40-11](https://user-images.githubusercontent.com/8076202/37556761-d96bcef6-2a13-11e8-939a-1633b175ca97.png)

converted:
![2018-03-17_18-46-36](https://user-images.githubusercontent.com/8076202/37556764-e76db942-2a13-11e8-8480-a9e20750d76b.png)

**Comment by iperov** [comment]
I trained only 3 hours :)

**Comment by iperov** [comment]
lol GAN even without mask gives superior result as on 3rd column 'masked' window.
even better than dfaker.
Face properly scaled. 
but convert uses 3rd column of 'raw' window
![python_2018-03-17_23-58-55](https://user-images.githubusercontent.com/8076202/37559431-7a1b25ba-2a3f-11e8-9014-a4676a265a9e.png)

**Comment by iperov** [comment]
no mask :(

![python_2018-03-18_09-45-29](https://user-images.githubusercontent.com/8076202/37563048-71e92552-2a91-11e8-9e20-fbd16a5634aa.png)

![2018-03-18_09-44-57](https://user-images.githubusercontent.com/8076202/37563050-73998752-2a91-11e8-9af4-665fe2d919aa.png)

so original model still best general purpose face swapper

**Comment by iperov** [comment]
conclusion: GAN still unusable for me. Nothing changed since initial GAN commit without 128 and vggface.

**Comment by Apollo122** [comment]
I'm training GAN128 model. I trained for 16k without PL and mask refinement. I'll continue with with PL for 10k then train more with refinement. But I don't think it will work. Will share the final results here

**Comment by iperov** [comment]
better mask with improved traindata generator?
https://github.com/deepfakes/faceswap/pull/307
![python_2018-03-23_00-32-21](https://user-images.githubusercontent.com/8076202/37796991-09fdc278-2e32-11e8-91ed-7acf79ae0824.png)

**Comment by cagkanciloglu** [comment]
Looks like there is an improvement. But you should try it with occlusions like hands. The masks I'm getting are like dotted pictures. I don't see dots on this picture. @oatssss had commented that he was trying get better masks by altering the generator.

**Comment by Apollo122** [comment]
Looks like an improvement but I don't know. You should try it with occlusions such as hands and see if it's handled. 
@oatssss commented that he was trying to get better results by altering the generator so it may be the way

**Comment by oatssss** [comment]
@iperov, shaoanlu made a mistake in his preview code: "raw" and "masked" are actually inverted (raw preview shows masked result, masked preview shows raw result). As for the color bug, try turning on seamless cloning, It should color correct so it's not as patchy as in the preview.

Are you guys able to get masks that properly handle occlusion with shaoanlu's? Something to try is change shaoanlu's notebook code so the model save/load code is compatible with this repo (it should be like a 3-line change), then use the converter here with the model trained via shaoanlu's.

Sorry guys, I haven't really been working on the project recently

**Comment by Apollo122** [comment]
It worked with mask refinement!!! Its not included in master so I did a [PR](https://github.com/deepfakes/faceswap/pull/308). Check the hand on raw preview. And yes its a bug like @oatssss mentions. I was looking at the masked all the time :) Although training took ages.
- 16k ite : No PL, no refinement
- 15k ite : With PL, no refinement
- 8k ite : With PL and refinement

Maybe with @iperov new trainer it takes less.

@Clorr please merge the PR I did. 

![a](https://user-images.githubusercontent.com/34627582/37851729-11130a86-2ef1-11e8-9c97-f249e1fbf9fc.png)

**Comment by Clorr** [comment]
done ;-)

**Comment by mul5kuq5pn** [comment]
Where would be the right spot for a guide how to use GAN(128) properly?
To me it is super confusing right now.
Also what is the correct data set to train with GAN?
Are frames with obstacles needed or should they be omitted?

**Comment by Apollo122** [comment]
Yes they are needed. I shared the options I used for the training. I also disabled and enabled mix_up for a couple of iterations but I don't think it mattered. What I can say about GAN is that you must have patience and faith :)

Note that I didn't try these options for GAN-64. Also there's no mask refinement option for it in the original repo. Maybe it works without it but I don't know.

**Comment by mul5kuq5pn** [comment]
@Apollo122 Thank you very much. The way you shared your options was a bit cryptic but I figured it out now. :)

**Comment by Apollo122** [comment]
Btw it seems that shaoanlu did some updates for v2 (one we are using). Automated training for perceptual loss and switching to proper loss functions at predefined iterations.
@oatssss fyi

**Comment by oatssss** [comment]
@Apollo122 how was your conversion with those results you got? Were they at least on par with the original model?
Thanks for the heads up on shaoanlu's stuff I'll look into it. Also, anyone can feel free to do the gan stuff.

**Comment by Apollo122** [comment]
@oatssss unfortunately it wasn't good enough, original is still better. The masks I got like dotted pictures maybe that interfered. Btw someone did a scripted version for gan. You may check PR's in gan repo.

**Comment by Apollo122** [comment]
@ruah1984 it's wasn't as good as original. Mask wasn't smooth enough and because it is applied on face it directly effects the quality
